development:
  adapter: 'sqlite3'
  encoding: unicode
  database: EcoFamily_development
  pool: 5
  username: zherk
  password: zherk
  host: localhost
  port: 5432

test:
  adapter: 'sqlite3'
  encoding: unicode
  database: EcoFamily_test
  pool: 5
  username: zherk
  password: zherk
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  pool: 5
  username: <%=ENV['OPENSHIFT_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_DB_PASSWORD']%>
  host: 127.9.102.129
  port: 5432
