development:
  adapter: <%= defined?(JRUBY_VERSION) ? 'jdbcpostgresql' : 'postgresql' %> 
  encoding: unicode
  database: EcoFamily_development
  pool: 5
  username: ecofam
  password: ecofam
  host: localhost
  port: 5432

test:
  adapter: <%= defined?(JRUBY_VERSION) ? 'jdbcpostgresql' : 'postgresql' %> 
  encoding: unicode
  database: EcoFamily_test
  pool: 5
  username: ecofam
  password: ecofam
  host: localhost
  port: 5432

production:
<% if defined?(JRUBY_VERSION) %>
  adapter: jdbc
  jndi: java:comp/env/jdbc/ecofam_rails
  driver: org.postgresql.Driver
<% else %>
  adapter: postgresql
  encoding: unicode
  database: EcoFamily_production
  pool: 5
  username: ecofam
  password: ecofam
  host: localhost
  port: 5432
<% end %>

